spring:
    config:
        activate:
            on-profile: default
    application:
        name: jpa.study
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:member;MODE=MySQL
        username: sa
        password: ''
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true         # 쿼리 로그 포맷 (정렬)
#                show_sql: false           # 쿼리 로그 출력
                use_sql_comments: true
                highlight_sql: true
#                default_batch_fetch_size : 10
    output:
        ansi:
            enabled: ALWAYS